### ISSUE TITLE
Fritz Dect 500 - Status is not updating

### ISSUE THREAD

**Issue by kaibuk** [tim-hellhake/fritz-adapter#11]
Hi 

I decided to create a seperate issue for that for visibility. So the problem is that the version recognise the bulbs. It does work, however the problem is that If change the status of the buld fomr a different device like a physical switch or from the Fritz Smart Home, the status is not being update on the Mozilla Iot interface.

The Fritz Smart Application does recognize the status if I control it using Mozilla IoT.

**Comment by kaibuk** [comment]
I tested now the version 2.0.0 and unfortunately the bulbs are showing as Disconnected now

I tried to reinstall the addon and reconfigure. The other devices like Heaters are being recognised as connected except the bulbs

Attached is the log file.

From the Log I can see following Errors

2020-10-27 20:00:46.083 ERROR  : Failed to get property on: getProperty: device: 130770002688-1 not found.
2020-10-27 20:00:46.084 ERROR  : Failed to get property brightness: getProperty: device: 130770002688-1 not found.
2020-10-27 20:00:46.084 ERROR  : Failed to get property colorPreset: getProperty: device: 130770002688-1 not found.
2020-10-27 20:00:46.085 ERROR  : Failed to get property on: getProperty: device: 130770020101-1 not found.
2020-10-27 20:00:46.086 ERROR  : Failed to get property brightness: getProperty: device: 130770020101-1 not found.
2020-10-27 20:00:46.087 ERROR  : Failed to get property colorPreset: getProperty: device: 130770020101-1 not found.

And

020-10-27 20:05:07.355 INFO   : fritz-adapter: Unhandled Rejection
2020-10-27 20:05:07.356 ERROR  : fritz-adapter: Error: User needs "HomeAuto" access rights
2020-10-27 20:05:07.357 ERROR  : fritz-adapter:     at Function.<anonymous> (/home/pi/.mozilla-iot/addons/fritz-adapter/lib/fritz-client.js:253:23)
2020-10-27 20:05:07.357 ERROR  : fritz-adapter:     at Generator.next (<anonymous>)
2020-10-27 20:05:07.358 ERROR  : fritz-adapter:     at fulfilled (/home/pi/.mozilla-iot/addons/fritz-adapter/lib/fritz-client.js:5:58)
2020-10-27 20:05:07.358 ERROR  : fritz-adapter:     at process._tickCallback (internal/process/next_tick.js:68:7)

However the account has all required permissions on the FritzBox

Let  me know if yo want me to do some more troubleshooting.

[Log 2.0.0.0.txt](https://github.com/tim-hellhake/fritz-adapter/files/5447875/Log.2.0.0.0.txt)

**Comment by tim-hellhake** [comment]
> However the account has all required permissions on the FritzBox

I'll remove the rights check and add a warning instead.
This should solve the issue.

**Comment by kaibuk** [comment]
I run now a command to delete the things just to make sure its something wrong in the cache

sqlite3 ~/.mozilla-iot/config/db.sqlite3 "DELETE FROM things"
sudo systemctl restart mozilla-iot-gateway

To see if that will work but unfortunately its hanging when its trying to add the bulb

2020-10-27 20:20:38.419 INFO   : fritz-adapter: Adapter: FritzAdapter id FritzAdapter pairing started
2020-10-27 20:20:38.425 INFO   : fritz-adapter: Detected new Comet DECT with ain 119600012296
2020-10-27 20:20:38.618 INFO   : fritz-adapter: setCachedValueAndNotify for property settemperature from undefined to 16.5 for 119610296464
2020-10-27 20:20:38.814 INFO   : fritz-adapter: setCachedValueAndNotify for property temperature from undefined to 21 for 119600012296
2020-10-27 20:20:39.044 INFO   : fritz-adapter: Detected new Comet DECT with ain 119600947448
2020-10-27 20:20:39.235 INFO   : fritz-adapter: setCachedValueAndNotify for property settemperature from undefined to 13.5 for 119600012296
2020-10-27 20:20:39.426 INFO   : fritz-adapter: setCachedValueAndNotify for property temperature from undefined to 16 for 119600947448
2020-10-27 20:20:39.657 INFO   : fritz-adapter: Detected new Comet DECT with ain 119610469968
2020-10-27 20:20:39.856 INFO   : fritz-adapter: setCachedValueAndNotify for property settemperature from undefined to 14 for 119600947448
2020-10-27 20:20:40.190 INFO   : fritz-adapter: setCachedValueAndNotify for property temperature from undefined to 20.5 for 119610469968
2020-10-27 20:20:40.332 INFO   : fritz-adapter: Unhandled Rejection
2020-10-27 20:20:40.333 ERROR  : fritz-adapter: Error: User needs "HomeAuto" access rights
2020-10-27 20:20:40.334 ERROR  : fritz-adapter:     at Function.<anonymous> (/home/pi/.mozilla-iot/addons/fritz-adapter/lib/fritz-client.js:253:23)
2020-10-27 20:20:40.335 ERROR  : fritz-adapter:     at Generator.next (<anonymous>)
2020-10-27 20:20:40.335 ERROR  : fritz-adapter:     at fulfilled (/home/pi/.mozilla-iot/addons/fritz-adapter/lib/fritz-client.js:5:58)
2020-10-27 20:20:40.336 ERROR  : fritz-adapter:     at process._tickCallback (internal/process/next_tick.js:68:7)

I tried also a different account with full Admin Fritz Box permission but no success.

**Comment by kaibuk** [comment]
OK Sorry jsut see your command there will give it a try.



> 
> 
> > However the account has all required permissions on the FritzBox
> 
> I'll remove the rights check and add a warning instead.
> This should solve the issue.

OK Sorry jsut see your command there will give it a try.

**Comment by tim-hellhake** [comment]
> OK Sorry jsut see your command there will give it a try.

No need to apologize. I appreciate the effort.

**Comment by tim-hellhake** [comment]
I added a new log output which begins with `User rights:`.
I wonder what that will show in your case.

**Comment by kaibuk** [comment]
Is there a way from the command line to force the update as it still shows 2.0.0 on my syste. Or do i just need to wait for a moment?

**Comment by kaibuk** [comment]
OK I manually Replaced the files from Tar file and rebooted Device.

Now the Bulbs are being recognized again.

I checked the Color Temperatures and they work. 

But the damn one think still doesn't work :) where If I enable the lights using Dect 440 or the Fritz Smart Home it's not recogising the status. 

We are do a lot further with the colors Let me attach a new log file
[Log 2.0.0.1.txt](https://github.com/tim-hellhake/fritz-adapter/files/5448102/Log.2.0.0.1.txt)

**Comment by tim-hellhake** [comment]
> But the damn one think still doesn't work :) where If I enable the lights using Dect 440 or the Fritz Smart Home it's not recogising the status.

That's still TBD :grimacing:
I'm currently working on it :smile:

**Comment by tim-hellhake** [comment]
The fun part is I found a much more efficient way to update the other devices while searching for a way to get the bulb state.
If everything works as expected I can update all devices with one request.

**Comment by kaibuk** [comment]
Hi Tim

i tested now the update. I tested it by switching it off/on on DECT 440 and on the Fritz Smart Home app. I was changing the Temperature colors on the Smart Home app and the colors.

All works great the Bulb are showing constantly the latest status after changing it on a different device. 

We can close the call. it is really great as this will allow me now to expand my Smart Home project.

Thank you very much. I think you can ad in the Information about the addon that its fully support Dect 500.

Other Open Source Smart Home applications don't have it yet.

**Comment by kaibuk** [comment]
Issue can be closes. Thanks
